sunrise:
  sunriseapi:
    url: https://api.sunrise-sunset.org
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/manage"
  endpoint:
    health:
      enabled: true
spring:
  devtools:
    restart:
      enabled: false