
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-java-todos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-java-todos
  template:
    metadata:
      labels:
        app: springboot-java-todos
    spec:
      containers:
        - name: springboot-java-todos
          image: springboot-java-todos
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
