apiVersion: v1
kind: Service
metadata:
  name: springboot-java-todos-svc
  labels:
    app: springboot-java-todos
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: springboot-java-todos